"""First commit with users,posts and votes

Revision ID: 288a8fd8fa15
Revises: 
Create Date: 2022-07-05 16:21:25.974719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288a8fd8fa15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
