"""Added mode of interaction

Revision ID: 47dae16579f9
Revises: 79ce2497d09d
Create Date: 2022-07-05 18:55:47.411211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47dae16579f9'
down_revision = '79ce2497d09d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('direction', sa.SmallInteger(), nullable=False))
    op.add_column('votes', sa.Column('interact_mode', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'interact_mode')
    op.drop_column('votes', 'direction')
    # ### end Alembic commands ###
