"""Added direction to votes

Revision ID: 79ce2497d09d
Revises: 288a8fd8fa15
Create Date: 2022-07-05 16:23:59.366977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ce2497d09d'
down_revision = '288a8fd8fa15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('direction', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'direction')
    # ### end Alembic commands ###
